language: python
python:
  - "2.7"
# command to install dependencies
sudo: required
install: 
- "pip install -r requirements.txt"
# command to run tests
- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
- sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
- sudo apt-get update -qq
- sudo apt-get install -qq google-chrome-stable
# - npm install -g phantomjs
- npm install -g chromedriver
before_script:
- "export DISPLAY=:99.0"
- sh -e /etc/init.d/xvfb start

script: 
- cd main && lettuce -v 3 features/simple.feature chrome desktop-m
