language: c
# python:
#   - "2.7"
# command to install dependencies
os:
  # - linux
  - osx
sudo: required
# before_install:
# - chmod a+x init_mac.sh
install: 
# - brew install pyenv
# - pyenv install 2.7.5
- "sudo pip install -r requirements.txt"
#this is mac
- chmod 777 ./scripts/install_safridrive.sh
# - ./scripts/install_safridrive.sh
##End mac
- chmod 777 ./scripts/init_linux.sh
# command to run tests
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/install_safridrive.sh fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/init_linux.sh fi
# - ./scripts/init_linux.sh
before_script:
# - "export DISPLAY=:99.0"
# - sh -e /etc/init.d/xvfb start
- cd main
script: 
# - lettuce -v 3 features/student_home.feature chrome desktop-m
- lettuce -v 3 features/simple.feature safari desktop-m
# - lettuce -v 3 features/simple.feature chrome desktop-m
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then lettuce -v 3 features/simple.feature safari desktop-m fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lettuce -v 3 features/simple.feature chrome desktop-m fi