language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: 
- cd main && lettuce -v 3 main/features/simple.feature chrome desktop-m
