language: c
# python:
#   - "2.7"
# command to install dependencies
os:
  # - linux
  - osx
sudo: required
# before_install:
# - chmod a+x init_mac.sh
install: 
# - brew install pyenv
# - pyenv install 2.7.5
- "sudo pip install -r requirements.txt"
#this is mac
- curl -O http://selenium-release.storage.googleapis.com/2.48/SafariDriver.safariextz
- chmod 777 ./scripts/install_safridrive.sh
- ./scripts/install_safridrive.sh
# - java -jar standalone.jar

##End mac
# - chmod 777 ./scripts/init_linux.sh
# command to run tests
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /scripts/init_mac.sh; fi
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/init_linux.sh; fi
# - ./scripts/init_linux.sh
before_script:
# - "export DISPLAY=:99.0"
# - sh -e /etc/init.d/xvfb start
- cd main
script: 
# - lettuce -v 3 features/student_home.feature chrome desktop-m
- lettuce -v 3 features/simple.feature safari desktop-m
# - lettuce -v 3 features/simple.feature chrome desktop-m
